version: '3.9'

services:
  gcs_proxy:
    image: ghcr.io/guaychou/gcs-proxy:v0.0.1
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/app/config.yaml
      - GCS_SA_B64="examplebase64encodedjsonsa"
    volumes:
      - "./config.yaml:/app/config.yaml"