FROM rust:1.67-alpine3.17 as build-env
WORKDIR /app
ADD . /app
RUN apk add --no-cache musl-dev openssl-dev
RUN rustup component add rustfmt clippy 
RUN cargo fmt --all -- --check         \
    && cargo clippy
RUN RUSTFLAGS="-C link-arg=-s --cfg unsound_local_offset" cargo build --release

FROM gcr.io/distroless/static-debian11:nonroot-amd64
ENV TZ="Asia/Jakarta"
WORKDIR /app
COPY --from=build-env /app/target/release/gcs-proxy-apps /app
CMD ["./gcs-proxy-apps"]